"""create documents inventory timeline_events tables

Revision ID: c3d5f6560254
Revises: 238650538c3b
Create Date: 2026-08-24 08:37:30.284311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3d5f6560254'
down_revision: Union[str, Sequence[str], None] = '238650538c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', title || ' ' || coalesce(description, '') || ' ' || coalesce(category, ''))", persisted=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_search_vector', 'documents', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('timeline_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('MEMORY_CREATED', 'TASK_CREATED', 'TASK_COMPLETED', 'DOCUMENT_CREATED', 'INVENTORY_CREATED', 'INVENTORY_UPDATED', name='timeline_event_type'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', title)", persisted=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timeline_events_occurred_at', 'timeline_events', ['occurred_at'], unique=False)
    op.create_index('ix_timeline_events_search_vector', 'timeline_events', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('inventory_items',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('serial_number', sa.String(length=200), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', name || ' ' || coalesce(description, '') || ' ' || coalesce(category, '') || ' ' || coalesce(location, ''))", persisted=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_items_search_vector', 'inventory_items', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_items_search_vector', table_name='inventory_items', postgresql_using='gin')
    op.drop_table('inventory_items')
    op.drop_index('ix_timeline_events_search_vector', table_name='timeline_events', postgresql_using='gin')
    op.drop_index('ix_timeline_events_occurred_at', table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index('ix_documents_search_vector', table_name='documents', postgresql_using='gin')
    op.drop_table('documents')
    # ### end Alembic commands ###
    # Manually added: autogenerate does not drop the enum type it
    # implicitly created for timeline_events.event_type, which would
    # otherwise be left orphaned in the database after a downgrade.
    sa.Enum(name='timeline_event_type').drop(op.get_bind(), checkfirst=True)
